# See: https://github.com/marketplace/actions/github-action-for-yarn
# See: https://github.com/marketplace/actions/publish-docker

name: GitHub CI/CD

on:
  push:
    branches: [main]
    paths:
      - ".github/**"
      - "spring-workshop/**"
      - "Dockerfile"
      - "gulpfile.js"
      - "nginx.conf"
      - "yarn.lock"
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Generate HTML Files with Pug
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn run gulp build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
